## 52. Calendar Module

In [24]:
import calendar
mm, dd, yyyy = map(int, input().split())
print(calendar.day_name[calendar.weekday(yyyy, mm, dd)].upper())

 07 16 2021


FRIDAY


## 53. Time Delta

In [33]:
#!/bin/python3

import math
import os
import random
import re
import sys

# Complete the time_delta function below.
import datetime

def time_delta(t1, t2):
    t_1 = datetime.datetime.strptime(t1, '%a %d %b %Y %H:%M:%S %z')
    t_2 = datetime.datetime.strptime(t2, '%a %d %b %Y %H:%M:%S %z')
    
    return str(int(abs(t_1 - t_2).total_seconds()))

if __name__ == '__main__':

    t = int(input())

    for t_itr in range(t):
        t1 = input()

        t2 = input()

        delta = time_delta(t1, t2)
        
        print(delta)

 2
 Sun 10 May 2015 13:54:36 -0700
 Sun 10 May 2015 13:54:36 -0000


25200


 Sat 02 May 2015 19:54:36 +0530
 Fri 01 May 2015 13:54:36 -0000


88200


## 54. Array Mathematics

In [56]:
import numpy as np

n, m = map(int, input().split())
a = np.array(np.zeros([n, m]), int)
b = np.array(np.zeros([n, m]), int)

for i in range(n) :
    a[i] = list(map(int, input().split()))
    
for j in range(n) :
    b[j] = list(map(int, input().split()))
    
print(np.add(a, b))
print(np.subtract(a, b))
print(np.multiply(a, b))
print(np.floor_divide(a, b))
print(np.mod(a, b))
print(np.power(a, b))

 2 4
 1 2 3 4
 1 2 3 4
 5 6 7 7
 5 6 7 7


[[ 6  8 10 11]
 [ 6  8 10 11]]
[[-4 -4 -4 -3]
 [-4 -4 -4 -3]]
[[ 5 12 21 28]
 [ 5 12 21 28]]
[[0 0 0 0]
 [0 0 0 0]]
[[1 2 3 4]
 [1 2 3 4]]
[[    1    64  2187 16384]
 [    1    64  2187 16384]]
